# cloudbuild.yaml
# cloudbuild.yaml
timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "firebase-tools"]

  - name: "gcr.io/cloud-builders/firebase"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd firebase_seminar_app
        firebase deploy --only hosting --non-interactive

images: []
# No container images are built/pushed by Cloud Build
images: []
